<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260430005612 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create initial schema: app_user, food, school, student_group, recipe, recipe_ingredient, menu, menu_item';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE app_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, name VARCHAR(255) NOT NULL, crn VARCHAR(50) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_88BDF3E9E7927C74 ON app_user (email)');
        $this->addSql('CREATE TABLE food (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, taco_id VARCHAR(10) DEFAULT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(100) DEFAULT NULL, source VARCHAR(20) NOT NULL, energy DOUBLE PRECISION DEFAULT NULL, protein DOUBLE PRECISION DEFAULT NULL, carbohydrate DOUBLE PRECISION DEFAULT NULL, lipid DOUBLE PRECISION DEFAULT NULL, fiber DOUBLE PRECISION DEFAULT NULL, calcium DOUBLE PRECISION DEFAULT NULL, iron DOUBLE PRECISION DEFAULT NULL, magnesium DOUBLE PRECISION DEFAULT NULL, zinc DOUBLE PRECISION DEFAULT NULL, vitamin_a DOUBLE PRECISION DEFAULT NULL, vitamin_c DOUBLE PRECISION DEFAULT NULL, sodium DOUBLE PRECISION DEFAULT NULL, saturated_fat DOUBLE PRECISION DEFAULT NULL, added_sugar DOUBLE PRECISION DEFAULT NULL, ultra_processed BOOLEAN NOT NULL, contains_gluten BOOLEAN NOT NULL, contains_lactose BOOLEAN NOT NULL, allergens JSON DEFAULT NULL, season_months JSON DEFAULT NULL, correction_factor DOUBLE PRECISION DEFAULT NULL, cooking_factor DOUBLE PRECISION DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_food_name ON food (name)');
        $this->addSql('CREATE TABLE menu (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, menu_date DATE NOT NULL, meal_type VARCHAR(50) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, school_id INT NOT NULL, student_group_id INT NOT NULL, owner_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7D053A93C32A47EE ON menu (school_id)');
        $this->addSql('CREATE INDEX IDX_7D053A934DDF95DC ON menu (student_group_id)');
        $this->addSql('CREATE INDEX IDX_7D053A937E3C61F9 ON menu (owner_id)');
        $this->addSql('CREATE TABLE menu_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, portion_size DOUBLE PRECISION NOT NULL, servings INT NOT NULL, menu_id INT NOT NULL, food_id INT DEFAULT NULL, recipe_id INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D754D550CCD7E912 ON menu_item (menu_id)');
        $this->addSql('CREATE INDEX IDX_D754D550BA8E87C4 ON menu_item (food_id)');
        $this->addSql('CREATE INDEX IDX_D754D55059D8A214 ON menu_item (recipe_id)');
        $this->addSql('CREATE TABLE recipe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, preparation_method TEXT DEFAULT NULL, portions INT NOT NULL, cost_per_portion DOUBLE PRECISION DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, owner_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DA88B1377E3C61F9 ON recipe (owner_id)');
        $this->addSql('CREATE TABLE recipe_ingredient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gross_weight DOUBLE PRECISION NOT NULL, net_weight DOUBLE PRECISION NOT NULL, cost_per_kg DOUBLE PRECISION DEFAULT NULL, recipe_id INT NOT NULL, food_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_22D1FE1359D8A214 ON recipe_ingredient (recipe_id)');
        $this->addSql('CREATE INDEX IDX_22D1FE13BA8E87C4 ON recipe_ingredient (food_id)');
        $this->addSql('CREATE TABLE school (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, city VARCHAR(255) DEFAULT NULL, state VARCHAR(2) DEFAULT NULL, inep_code VARCHAR(20) DEFAULT NULL, owner_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_F99EDABB7E3C61F9 ON school (owner_id)');
        $this->addSql('CREATE TABLE student_group (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, age_group VARCHAR(30) NOT NULL, meal_period VARCHAR(20) NOT NULL, student_count INT NOT NULL, school_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E5F73D58C32A47EE ON student_group (school_id)');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A93C32A47EE FOREIGN KEY (school_id) REFERENCES school (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A934DDF95DC FOREIGN KEY (student_group_id) REFERENCES student_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu ADD CONSTRAINT FK_7D053A937E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D550CCD7E912 FOREIGN KEY (menu_id) REFERENCES menu (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D550BA8E87C4 FOREIGN KEY (food_id) REFERENCES food (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE menu_item ADD CONSTRAINT FK_D754D55059D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe ADD CONSTRAINT FK_DA88B1377E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_ingredient ADD CONSTRAINT FK_22D1FE1359D8A214 FOREIGN KEY (recipe_id) REFERENCES recipe (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE recipe_ingredient ADD CONSTRAINT FK_22D1FE13BA8E87C4 FOREIGN KEY (food_id) REFERENCES food (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE school ADD CONSTRAINT FK_F99EDABB7E3C61F9 FOREIGN KEY (owner_id) REFERENCES app_user (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE student_group ADD CONSTRAINT FK_E5F73D58C32A47EE FOREIGN KEY (school_id) REFERENCES school (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE menu DROP CONSTRAINT FK_7D053A93C32A47EE');
        $this->addSql('ALTER TABLE menu DROP CONSTRAINT FK_7D053A934DDF95DC');
        $this->addSql('ALTER TABLE menu DROP CONSTRAINT FK_7D053A937E3C61F9');
        $this->addSql('ALTER TABLE menu_item DROP CONSTRAINT FK_D754D550CCD7E912');
        $this->addSql('ALTER TABLE menu_item DROP CONSTRAINT FK_D754D550BA8E87C4');
        $this->addSql('ALTER TABLE menu_item DROP CONSTRAINT FK_D754D55059D8A214');
        $this->addSql('ALTER TABLE recipe DROP CONSTRAINT FK_DA88B1377E3C61F9');
        $this->addSql('ALTER TABLE recipe_ingredient DROP CONSTRAINT FK_22D1FE1359D8A214');
        $this->addSql('ALTER TABLE recipe_ingredient DROP CONSTRAINT FK_22D1FE13BA8E87C4');
        $this->addSql('ALTER TABLE school DROP CONSTRAINT FK_F99EDABB7E3C61F9');
        $this->addSql('ALTER TABLE student_group DROP CONSTRAINT FK_E5F73D58C32A47EE');
        $this->addSql('DROP TABLE app_user');
        $this->addSql('DROP TABLE food');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE menu_item');
        $this->addSql('DROP TABLE recipe');
        $this->addSql('DROP TABLE recipe_ingredient');
        $this->addSql('DROP TABLE school');
        $this->addSql('DROP TABLE student_group');
    }
}
